type FaqTone = "indigo" | "ocean" | "plum" | "ember";

// Keep semantic accents paired with the matching SVG scene.
export const FAQ_TONES: Readonly<Record<string, FaqTone>> = {
  "first-start": "indigo",
  "connection": "ocean",
  "workout-start": "indigo",
  "reschedule": "plum",
  "illness-pause": "ocean",
  "nutrition-add": "ember",
  "nutrition-label": "ocean",
  "daily-water": "ocean",
  "supplements": "plum",
  "notifications": "plum",
  "progress": "ocean",
  "plus": "plum",
  "ai-trainer": "plum",
  "friends": "plum",
  "offline": "indigo",
  "support": "plum",
  "nutrition-goal": "ember",
  "nutrition-foundation": "ocean",
  "nutrition-protein": "plum",
  "nutrition-around-workout": "ember",
  "nutrition-hydration": "ocean",
  "nutrition-supplements": "plum",
  "working-weight": "indigo",
  "load-phases": "plum",
  "warmup-sets": "indigo",
  "warmup": "ember",
  "cardio-before": "ocean",
  "failure": "plum",
  "rest-between-sets": "ocean",
  "progress-without-weight": "indigo",
  "stop-workout": "ember",
};
